### PR TITLE
Add extraction endpoint

### PR DESCRIPTION
**Pull request by diogob**
Add ruby resource to use the [Autofill feature](https://documentation.onfido.com/#autofill-(beta))

When I try to use this endpoint I'm consistently getting a `classification_failure`, but it seems to be an account issue (I got the same error when testing with curl).

### CODE REVIEW

**Comment by alanjc7** [comment]
Hey @diogob, thanks for opening a PR!  

We are still in the process of making autofill a full feature - it's currently still in beta - which is why we haven't added it to the libraries already. 

We hope this will be done in the coming weeks so will hold off merging this until then.

**Comment by diogob** [comment]
@alanjc7 any status update on when this feature will be out of beta? Moreover, in case I want to use it during beta, is there any caveat I should be aware of? Any potential road blocker to consume data from the beta endpoint?

**Comment by ciaran16** [comment]
Hi @diogob, sorry for the slow response, Alan is currently away but I'll look into whether this can be merged and get back to you next week.

I think you'll need to contact client-support@onfido.com about using this during beta and for any caveats.

**Comment by olasitarska** [comment]
Hey @diogob - just to bring some clarity here. It looks like we might be taking this feature out of beta in Q1 2021, so still quite a while away.

**Comment by olasitarska** [comment]
Good news! We have decided to include this endpoint in the library regardless of the feature still being in beta.

**Pull request merged**
